---
- name: collect facts
  setup: ~

# - name: ensure drop-in directories
#   file:
#     state: directory
#     path: "{{ dockerd_dropin_path | dirname }}"
#     owner: root
#     group: root
#     mode: "0755"

- name: ensure APT over HTTP requirements
  apt:
    update_cache: true
    install_recommends: false
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - gnupg2
      - software-properties-common

- name: ensure Docker Engine APT key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: ensure Docker Engine APT repository
  apt_repository:
    filename: docker
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

- name: ensure Docker Engine
  apt:
    update_cache: true
    install_recommends: false
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

# - name: "ensure drop-in {{ dockerd_dropin_path }}"
#   notify: restart service docker
#   copy:
#     dest: "{{ dockerd_dropin_path }}"
#     owner: root
#     group: root
#     mode: "0644"
#     content: |
#       [Service]
#       ExecStart=
#       ExecStart=/usr/bin/dockerd --host=fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd --iptables={{ docker_daemon_opts_iptables }} --ip-forward={{ docker_daemon_opts_ipforward }} --ip-masq={{ docker_daemon_opts_ipmasq }} --raw-logs={{ docker_daemon_opts_raw_logs }} --log-opt=max-file={{ dockerd_log_max_files }} --log-opt=max-size={{ dockerd_log_max_size }}


- name: ensure module "docker-py"
  pip:
    name: docker-py
    state: present
  when: ansible_facts.python.version.major is version('2', '=')

- block:
    - name: delete deprecated module "docker-py"
      pip:
        executable: pip3
        name: docker-py
        state: absent
    - name: ensure pip3 modules
      pip:
        executable: pip3
        name: [six, docker]
        state: present
  when: ansible_facts.python.version.major is version('3', '=')

- name: ensure docker is started and enabled
  systemd:
    name: docker
    daemon_reload: true
    enabled: true
    state: started

- name: execute handlers
  meta: flush_handlers
